# .travis.yml for arduino projects
language: python
python:
  - "2.7"
sudo: false
cache:
  directories:
    - "~/.platformio"
addons:
  apt:
    packages:
      - cppcheck
      - astyle

install:
  - pip install -U platformio

script:
  - cppcheck --version
  - cppcheck --error-exitcode=1 --enable=warning,style,performance,portability -v --language=c src/*.ino
  # check if any style violation is found
  - astyle --version
  - astyle --formatted --options=.astylerc --recursive 'src/*.ino' | tee astyle.log
  # exit with non-zero when found
  - grep -v '^Formatted' astyle.log
  - for i in `awk '/^Formatted/ { print $2 }' astyle.log`; do diff -u src/${i}.orig src/${i}; done
  - PLATFORMIO_SRC_BUILD_FLAGS="-DTHINGSPEAK_API_CHANNEL=1 -DTHINGSPEAK_API_KEY=THINGSPEAK_API_KEY" pio run -v
